tests: virpcimock: remove unused variable 'devid'
virpcimock.c:685:26: error: unused variable 'devid' [-Werror,-Wunused-variable]
    VIR_AUTOFREE(char *) devid = NULL;
                         ^

Fixes: 76b42294380d40282ed29560e4ae4a7491b9df05

Signed-off-by: Ján Tomko <jtomko@redhat.com>