lxc: fix starting a domain with non-strict numa memory mode
 # virsh -c lxc:/// start helloworld
 error: Failed to start domain helloworld
 error: internal error: guest failed to start: Unknown
 failure in libvirt_lxc startup

Return success when there are no cpuset.mems to be set,
instead of failing without setting an error.

Signed-off-by: Ján Tomko <jtomko@redhat.com>
(cherry picked from commit 930e8697a5b66989fbf56a5e38cfaf1378a1c59e)