travis: fix homebrew install of python3
The Python3 package has started failing to install from
HomeBrew with the following:

  Error: The `brew link` step did not complete successfully
  The formula built, but is not symlinked into /usr/local
  Could not symlink Frameworks/Python.framework/Headers
  Target /usr/local/Frameworks/Python.framework/Headers
  is a symlink belonging to python@2. You can unlink it:

    brew unlink python@2

  To force the link and overwrite all conflicting files:

    brew link --overwrite python

The result is that libvirt fails to find python3:

  checking for python3... no
  configure: error: 'python3' binary is required to build libvirt

It is unclear what changed in Travis/HomeBrew to break our
previously working setup, but running the suggested command
fixes it well enough for libvirt's CI needs.

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>