tests: fix warning with old GCC about missing struct initializer
Old GCC isn't happy about the {0} initializer because the first
field in the struct is itself a struct.

../../tests/openvzutilstest.c: In function 'testReadNetworkConf':
../../tests/openvzutilstest.c:101:12: error: missing braces around initializer [-Werror=missing-braces]
     struct openvz_driver driver = {0};
            ^

This fixes commit 4a4132b4625778cf80acb9c92d06351b44468ac3

Signed-off-by: Daniel Berrange <berrange@localhost.localdomain>